### ISSUE TITLE
Missing required modules: 'Alamofire', 'CryptoSwift'

### ISSUE THREAD

**Issue by rs-conti** [wl-online-payments-direct/sdk-client-flutter#2]
Hello,

There seems to be an issue with the iOS part of the SDK (Android works fine).

Indeed, when I try to build the iOS app, I face the following issue:

![image](https://github.com/wl-online-payments-direct/sdk-client-flutter/assets/166706741/0ca937d2-4510-47fa-a967-c320258333b5)

I tried several things to solve this (along with a `pod install/update`), to no avail:

- `flutter clean`.
- Deleting the `DerivedData` directory.
- Manually adding `Alamofire` and `CryptoSwift` to the `Podfile`.

I encountered this issue with version `1.0.1` and `1.1.0` of the Payments SDK.

My setup:

| Tool                  | Version |
|-----------------------|---------|
| Flutter               | 3.19.3  |
| Dart                  | 3.3.1   |
| Payments SDK          | 1.1.0   |
| Xcode                 | 15.3    |
| iOS Deployment Target | 16.0    |

Do you have any input on this?

Thanks a lot.

**Comment by worldline-direct-support-team** [comment]
Hello rs-conti,

Thank you for sending a bug-report! 
We have found an issue with the way that the dependencies were resolved. Therefore we have released a fix: version 1.1.1 of the SDK should resolve the missing dependencies properly. 
Please note that when you have updated the version of our SDK, you should execute a `pod install`, causing the dependencies to resolve.

Thank you for reaching out, and good luck developing with our SDK!

Kind regards,
Worldline support

**Comment by rs-conti** [comment]
Hi,

That's great, thanks!
