### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by cedvdb** [wl-online-payments-direct/sdk-client-flutter#4]
Can you add web support ?

**Comment by worldline-direct-support-team** [comment]
Hi cedvdb,

Can you please be more specific? Do you want us to also enable this SDK for the web? If so, this is not planned. For the web, please use our [JS Client SDK](https://github.com/wl-online-payments-direct/sdk-client-js).

Kind regards,
Worldline Support Team

**Comment by cedvdb** [comment]
@worldline-direct-support-team

  > Can you please be more specific?

 Flutter is a multi platform framework targetting android, ios as well as the web platform (as well as windows and linux). Adding the web platform (via the js client) would be helpful.

**Comment by worldline-direct-support-team** [comment]
Hi [cedvdb](https://github.com/cedvdb),

We will put this to our backlog and let you know once we do it.

Kind regards,
Worldline Support Team
